development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_development
  pool: 5
  username: blog_app
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: blog_app_test
  pool: 5
  username: blog_app
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: blog_app_production
  pool: 5
  username: blog_app
  password: